[tools]
remodel = { github = "rojo-rbx/remodel", version = "0.11.0" }
rojo = { github = "rojo-rbx/rojo", version = "7.2.1" }
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { github = "Kampfkarren/selene", version = "0.24.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.16.0" }