name: CI

on:
  push:
    branches:
    - master
  
  pull_request:
    branches:
    - master

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Foreman
      uses: Roblox/setup-foreman@v1
      with:
        version: "1.1.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Lint
      run: selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "v0.16.0"
          args: --check ./src

  tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "1.1.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Roblox test place
        run: rojo build unitTesting.project.json -o places/unitTestingBuild.rbxlx

      - name: Run tests
        run: run-in-roblox --place places/unitTestingBuild.rbxlx --script tests/TestBootstrap.server.lua

      